site_name: My Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Quarkus:
      - Intro: Quarkus/intro.md
           - Lets handle Quarkus together step by step:
               - Quarkus Fundamentals: quarkus_fundamentals.md
               - Setup & Project Creation: setup_project_creation.md