site_name: My Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Quarkus:
      - Intro: Quarkus/intro.md
      - Quarkus Fundamentals: Quarkus/quarkus_fundamentals.md
      - Setup & Project Creation: Quarkus/setup_project_creation.md
      - Dependency Injection and Beans: Quarkus/Dependency_Injection_and_Beans.md
